all :     mcmc_steps results
					python main.py

mcmc_steps :
					mkdir mcmc_steps
					mkdir mcmc_steps/dust_on
					mkdir mcmc_steps/dust_off

results :
					mkdir results

clean :
					rm -Rf *.pyc *~
